[build]
  command = "npm run build"
  publish = ".output/public"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "#custom"

[build.environment]
  NODE_VERSION = "22"


[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/javascript"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
