import type { StateItem } from '~/types/article'

export const STATES: string[] = [
  'Nacional',
  'Acre',
  'Alagoas',
  'Amapá',
  'Amazonas',
  'Bahia',
  'Ceará',
  'Distrito Federal',
  'Espírito Santo',
  'Goiás',
  'Maranhão',
  'Mato Grosso',
  'Mato Grosso do Sul',
  'Minas Gerais',
  'Pará',
  'Paraíba',
  'Paraná',
  'Pernambuco',
  'Piauí',
  'Rio de Janeiro',
  'Rio Grande do Norte',
  'Rio Grande do Sul',
  'Rondônia',
  'Roraima',
  'Santa Catarina',
  'São Paulo',
  'Sergipe',
  'Tocantins',
]

export const HOME_STATES: StateItem[] = [
  { id: 'Nacional', name: 'Nacional' },
  { id: 'Amazonas', name: 'Amazonas' },
  { id: 'Pará', name: 'Pará' },
  { id: 'Mato Grosso', name: 'Mato Grosso' },
  { id: 'Minas Gerais', name: 'Minas Gerais' },
  { id: 'São Paulo', name: 'São Paulo' },
  { id: 'Bahia', name: 'Bahia' },
  { id: 'Pernambuco', name: 'Pernambuco' },
  { id: 'Maranhão', name: 'Maranhão' },
  { id: 'Paraná', name: 'Paraná' },
  { id: 'Rio Grande do Sul', name: 'Rio Grande do Sul' },
]
